name: 'storybook-chromatic-link-comment'
description: 'Leaves a comment with a link to storybook for the branch of a pr'
author: 'Daniel Williams'
color: 'pink'
icon: 'book-open'
inputs:
  github-token:
    required: true
    description: 'Token used to authenticate with the GitHub API'
  app-id:
    required: true
    description: 'Your chromatic app id used to create the link'
runs:
  using: 'node18'
  main: 'dist/index.js'
